/**
 * Comprehensive question framework for document creation
 * Includes tiered questions (Basic/Advanced) for Ontario & Federal legal compliance
 * 
 * LEGAL COMPLIANCE NOTES:
 * - Wills: Succession Law Reform Act (SLRA), Estates Act
 * - POA Property: Powers of Attorney Act
 * - POA Personal Care: Health Care Consent Act, Substitute Decisions Act
 */

export interface Question {
  id: number;
  section: string;
  question: string;
  field: string;
  type: 'text' | 'date' | 'textarea' | 'select' | 'checkbox' | 'number';
  options?: string[];
  required: boolean;
  tier: 'basic' | 'advanced'; // basic = free users, advanced = premium
  helpText?: string;
  legalNote?: string;
}

export interface DocumentQuestionSet {
  documentType: 'will' | 'poa-property' | 'poa-personal-care';
  questions: Question[];
}

// ============================================================================
// WILL QUESTIONS - Ontario Succession Law Reform Act Compliant
// ============================================================================

export const WILL_QUESTIONS: Question[] = [
  // SECTION 1: TESTATOR INFORMATION (Legal Requirements)
  {
    id: 1,
    section: 'Testator Information',
    question: 'What is your full legal name (including any maiden names, aliases, or names you\'ve been known by)?',
    field: 'testatorFullName',
    type: 'text',
    required: true,
    tier: 'basic',
    legalNote: 'Required for will validity under Succession Law Reform Act',
  },
  {
    id: 2,
    section: 'Testator Information',
    question: 'What is your date of birth?',
    field: 'testatorDateOfBirth',
    type: 'date',
    required: true,
    tier: 'basic',
    legalNote: 'Confirms testator is of legal age (18+) as required by law',
  },
  {
    id: 3,
    section: 'Testator Information',
    question: 'What is your current residential address in Ontario?',
    field: 'testatorAddress',
    type: 'textarea',
    required: true,
    tier: 'basic',
    helpText: 'Include street address, city, province, and postal code',
    legalNote: 'Establishes Ontario jurisdiction for will execution',
  },
  {
    id: 4,
    section: 'Testator Information',
    question: 'How long have you been a resident of Ontario?',
    field: 'ontarioResidency',
    type: 'text',
    required: true,
    tier: 'basic',
    helpText: 'e.g., "5 years" or "since 2020"',
    legalNote: 'Confirms jurisdiction for probate purposes',
  },
  {
    id: 5,
    section: 'Testator Information',
    question: 'Are you of sound mind and free from undue influence?',
    field: 'soundMind',
    type: 'select',
    options: ['Yes', 'No', 'Unsure'],
    required: true,
    tier: 'basic',
    legalNote: 'Testamentary capacity is essential for will validity',
  },
  {
    id: 6,
    section: 'Testator Information',
    question: 'Have you ever been declared mentally incapable by a court?',
    field: 'mentalCapacity',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'basic',
    legalNote: 'Affects will validity and capacity to make decisions',
  },

  // SECTION 2: MARITAL STATUS & FAMILY LAW CONSIDERATIONS
  {
    id: 7,
    section: 'Marital & Family Status',
    question: 'What is your current marital status?',
    field: 'maritalStatus',
    type: 'select',
    options: ['Single', 'Married', 'Common-law (3+ years)', 'Divorced', 'Widowed', 'Separated'],
    required: true,
    tier: 'basic',
    legalNote: 'Marital status affects spousal rights under Family Law Act',
  },
  {
    id: 8,
    section: 'Marital & Family Status',
    question: 'If married or common-law, what is your spouse\'s full legal name and date of birth?',
    field: 'spouseInfo',
    type: 'textarea',
    required: false,
    tier: 'basic',
    helpText: 'Include full legal name and DOB for spousal rights verification',
  },
  {
    id: 9,
    section: 'Marital & Family Status',
    question: 'Have you been married or in a common-law relationship before?',
    field: 'previousMarriages',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'basic',
    legalNote: 'Previous marriages may affect spousal support obligations',
  },
  {
    id: 10,
    section: 'Marital & Family Status',
    question: 'If yes to previous relationships, provide details (names, dates, children from those relationships)',
    field: 'previousMarriageDetails',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'Important for identifying all potential beneficiaries and dependents',
  },
  {
    id: 11,
    section: 'Marital & Family Status',
    question: 'Do you have a marriage contract, cohabitation agreement, or prenuptial agreement?',
    field: 'marriageContract',
    type: 'select',
    options: ['Yes', 'No', 'Unsure'],
    required: true,
    tier: 'advanced',
    legalNote: 'These agreements may override will provisions under Family Law Act',
  },
  {
    id: 12,
    section: 'Marital & Family Status',
    question: 'If yes, please provide details of the agreement (date signed, key terms)',
    field: 'marriageContractDetails',
    type: 'textarea',
    required: false,
    tier: 'advanced',
  },

  // SECTION 3: CHILDREN & DEPENDENTS
  {
    id: 13,
    section: 'Children & Dependents',
    question: 'Do you have any children (biological, adopted, or step-children)?',
    field: 'hasChildren',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'basic',
    legalNote: 'Children have statutory rights to share in estate under Succession Law Reform Act',
  },
  {
    id: 14,
    section: 'Children & Dependents',
    question: 'If yes, list all children with full names, dates of birth, and current ages',
    field: 'childrenList',
    type: 'textarea',
    required: false,
    tier: 'basic',
    helpText: 'Include biological, adopted, and step-children. Format: Name (DOB) - Age',
  },
  {
    id: 15,
    section: 'Children & Dependents',
    question: 'Do you have any grandchildren? If yes, list their names and parents',
    field: 'grandchildren',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'Important if you want to provide for grandchildren in case of parent\'s death',
  },
  {
    id: 16,
    section: 'Children & Dependents',
    question: 'Are there any other individuals who depend on you financially (parents, siblings, etc.)?',
    field: 'otherDependents',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    legalNote: 'Dependents may have claims under Succession Law Reform Act s. 58',
  },
  {
    id: 17,
    section: 'Children & Dependents',
    question: 'Are there any family members you intentionally wish to exclude from your will?',
    field: 'excludedFamily',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
    helpText: 'If yes, you should explain why to prevent claims against the estate',
  },
  {
    id: 18,
    section: 'Children & Dependents',
    question: 'If yes, provide names and reasons for exclusion',
    field: 'exclusionReasons',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    legalNote: 'Explicit exclusion helps prevent dependant support claims',
  },
  {
    id: 19,
    section: 'Children & Dependents',
    question: 'Do any of your children have special circumstances (disabilities, substance issues, financial irresponsibility)?',
    field: 'childrenSpecialCircumstances',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'May require special trust arrangements (e.g., Henson Trust)',
  },
  {
    id: 20,
    section: 'Children & Dependents',
    question: 'Do you have a blended family situation?',
    field: 'hasBlendedFamily',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
    legalNote: 'Blended families require careful planning to avoid disputes',
  },
  {
    id: 21,
    section: 'Children & Dependents',
    question: 'If yes, describe how you want assets distributed between your spouse and children',
    field: 'blendedFamilyPlan',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'Specify what goes to spouse vs. children to avoid ambiguity',
  },

  // SECTION 4: REAL PROPERTY
  {
    id: 22,
    section: 'Real Property',
    question: 'Do you own your primary residence?',
    field: 'ownsPrimaryResidence',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'basic',
  },
  {
    id: 23,
    section: 'Real Property',
    question: 'If yes, provide address and estimated current market value',
    field: 'primaryResidenceDetails',
    type: 'textarea',
    required: false,
    tier: 'basic',
    helpText: 'Include full address and approximate value for estate planning',
  },
  {
    id: 24,
    section: 'Real Property',
    question: 'Is there a mortgage on your primary residence?',
    field: 'hasMortgage',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'basic',
  },
  {
    id: 25,
    section: 'Real Property',
    question: 'If yes, provide lender name and approximate remaining balance',
    field: 'mortgageDetails',
    type: 'textarea',
    required: false,
    tier: 'basic',
    helpText: 'Important for determining net estate value',
  },
  {
    id: 26,
    section: 'Real Property',
    question: 'Do you own any investment properties (rental, commercial)?',
    field: 'ownsInvestmentProperties',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'basic',
  },
  {
    id: 27,
    section: 'Real Property',
    question: 'If yes, list addresses, property types, and estimated values',
    field: 'investmentPropertiesDetails',
    type: 'textarea',
    required: false,
    tier: 'basic',
  },
  {
    id: 28,
    section: 'Real Property',
    question: 'Do you own any vacation or cottage properties?',
    field: 'ownsVacationProperty',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 29,
    section: 'Real Property',
    question: 'If yes, provide details (location, value, any mortgages)',
    field: 'vacationPropertyDetails',
    type: 'textarea',
    required: false,
    tier: 'advanced',
  },
  {
    id: 30,
    section: 'Real Property',
    question: 'Is any real property owned jointly with others (joint tenancy)?',
    field: 'hasJointOwnership',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
    legalNote: 'Joint tenancy property passes by right of survivorship, not through will',
  },
  {
    id: 31,
    section: 'Real Property',
    question: 'If yes, provide details (property, co-owners, ownership percentage)',
    field: 'jointOwnershipDetails',
    type: 'textarea',
    required: false,
    tier: 'advanced',
  },
  {
    id: 32,
    section: 'Real Property',
    question: 'How would you like your real property to be distributed?',
    field: 'propertyDistribution',
    type: 'textarea',
    required: false,
    tier: 'basic',
    helpText: 'Specify which beneficiary gets which property',
  },

  // SECTION 5: FINANCIAL ASSETS
  {
    id: 33,
    section: 'Financial Assets',
    question: 'List all bank accounts (institution, account type, approximate balance)',
    field: 'bankAccounts',
    type: 'textarea',
    required: false,
    tier: 'basic',
    helpText: 'Include chequing, savings, and any joint accounts',
  },
  {
    id: 34,
    section: 'Financial Assets',
    question: 'Do you have investment accounts (stocks, bonds, mutual funds)?',
    field: 'hasInvestmentAccounts',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'basic',
  },
  {
    id: 35,
    section: 'Financial Assets',
    question: 'If yes, list institutions and approximate values',
    field: 'investmentAccountsDetails',
    type: 'textarea',
    required: false,
    tier: 'basic',
  },
  {
    id: 36,
    section: 'Financial Assets',
    question: 'Do you have registered retirement savings plans (RRSPs)?',
    field: 'hasRRSPs',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'basic',
    legalNote: 'RRSPs pass to named beneficiary, not through will',
  },
  {
    id: 37,
    section: 'Financial Assets',
    question: 'If yes, list institutions, values, and current beneficiary designations',
    field: 'rrspsDetails',
    type: 'textarea',
    required: false,
    tier: 'basic',
    helpText: 'Include who is currently named as beneficiary',
  },
  {
    id: 38,
    section: 'Financial Assets',
    question: 'Do you have tax-free savings accounts (TFSAs)?',
    field: 'hasTFSAs',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'basic',
    legalNote: 'TFSAs pass to named beneficiary, not through will',
  },
  {
    id: 39,
    section: 'Financial Assets',
    question: 'If yes, list institutions, values, and current beneficiary designations',
    field: 'tfsasDetails',
    type: 'textarea',
    required: false,
    tier: 'basic',
  },
  {
    id: 40,
    section: 'Financial Assets',
    question: 'Do you have GICs or other fixed income investments?',
    field: 'hasGICs',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 41,
    section: 'Financial Assets',
    question: 'If yes, provide details (institution, value, maturity date)',
    field: 'gicsDetails',
    type: 'textarea',
    required: false,
    tier: 'advanced',
  },
  {
    id: 42,
    section: 'Financial Assets',
    question: 'Do you receive or are entitled to any pensions?',
    field: 'hasPensions',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
    legalNote: 'Pension benefits may have survivor benefits and designated beneficiaries',
  },
  {
    id: 43,
    section: 'Financial Assets',
    question: 'If yes, provide details (employer/plan, estimated monthly benefit, survivor options)',
    field: 'pensionsDetails',
    type: 'textarea',
    required: false,
    tier: 'advanced',
  },
  {
    id: 44,
    section: 'Financial Assets',
    question: 'Do you have life insurance policies?',
    field: 'hasLifeInsurance',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'basic',
    legalNote: 'Life insurance proceeds pass to named beneficiary, not through will',
  },
  {
    id: 45,
    section: 'Financial Assets',
    question: 'If yes, list policies, coverage amounts, and current beneficiaries',
    field: 'lifeInsuranceDetails',
    type: 'textarea',
    required: false,
    tier: 'basic',
    helpText: 'Include policy numbers and who is currently named as beneficiary',
  },
  {
    id: 46,
    section: 'Financial Assets',
    question: 'Do you have any annuities?',
    field: 'hasAnnuities',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 47,
    section: 'Financial Assets',
    question: 'If yes, provide details (issuer, value, terms, beneficiary)',
    field: 'annuitiesDetails',
    type: 'textarea',
    required: false,
    tier: 'advanced',
  },
  {
    id: 48,
    section: 'Financial Assets',
    question: 'Do you have a safe deposit box?',
    field: 'hasSafeDepositBox',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 49,
    section: 'Financial Assets',
    question: 'If yes, where is it located and what does it contain?',
    field: 'safeDepositBoxDetails',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'Include bank name, box number (if safe to share), and contents',
  },
  {
    id: 50,
    section: 'Financial Assets',
    question: 'Estimate your total financial assets (excluding real estate)',
    field: 'totalFinancialAssets',
    type: 'text',
    required: false,
    tier: 'basic',
    helpText: 'Approximate total for estate planning purposes',
  },

  // SECTION 6: BUSINESS INTERESTS
  {
    id: 51,
    section: 'Business Interests',
    question: 'Do you own or have an interest in any business?',
    field: 'ownsBusinessInterest',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 52,
    section: 'Business Interests',
    question: 'If yes, describe the business and your ownership percentage',
    field: 'businessDetails',
    type: 'textarea',
    required: false,
    tier: 'advanced',
  },
  {
    id: 53,
    section: 'Business Interests',
    question: 'What type of business is it (sole proprietorship, partnership, corporation)?',
    field: 'businessType',
    type: 'select',
    options: ['Sole Proprietorship', 'Partnership', 'Corporation', 'LLC', 'Other'],
    required: false,
    tier: 'advanced',
  },
  {
    id: 54,
    section: 'Business Interests',
    question: 'What is the estimated value of your business interest?',
    field: 'businessValue',
    type: 'text',
    required: false,
    tier: 'advanced',
  },
  {
    id: 55,
    section: 'Business Interests',
    question: 'Is there a buy-sell agreement in place?',
    field: 'hasBuySellAgreement',
    type: 'select',
    options: ['Yes', 'No', 'Unsure'],
    required: false,
    tier: 'advanced',
    legalNote: 'Buy-sell agreements override will provisions for business interests',
  },
  {
    id: 56,
    section: 'Business Interests',
    question: 'If yes, provide details (date, key terms, valuation method)',
    field: 'buySellAgreementDetails',
    type: 'textarea',
    required: false,
    tier: 'advanced',
  },
  {
    id: 57,
    section: 'Business Interests',
    question: 'How should your business interest be handled after your death?',
    field: 'businessSuccession',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'e.g., sold, transferred to family member, liquidated',
  },

  // SECTION 7: DIGITAL & CRYPTOCURRENCY ASSETS
  {
    id: 58,
    section: 'Digital & Crypto Assets',
    question: 'Do you own any cryptocurrency (Bitcoin, Ethereum, etc.)?',
    field: 'hasCryptocurrency',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
    legalNote: 'Cryptocurrency is treated as personal property under Ontario law',
  },
  {
    id: 59,
    section: 'Digital & Crypto Assets',
    question: 'If yes, provide details and estimated value',
    field: 'cryptocurrencyDetails',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'Include types, exchanges, and approximate values',
  },
  {
    id: 60,
    section: 'Digital & Crypto Assets',
    question: 'Do you have digital accounts (PayPal, online banking, etc.)?',
    field: 'hasDigitalAccounts',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 61,
    section: 'Digital & Crypto Assets',
    question: 'If yes, list them (do not include passwords)',
    field: 'digitalAccountsList',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'List account types and where to find login information',
  },
  {
    id: 62,
    section: 'Digital & Crypto Assets',
    question: 'Do you own any online businesses, websites, or domains?',
    field: 'hasOnlineBusiness',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 63,
    section: 'Digital & Crypto Assets',
    question: 'If yes, provide details and estimated value',
    field: 'onlineBusinessDetails',
    type: 'textarea',
    required: false,
    tier: 'advanced',
  },

  // SECTION 8: PERSONAL PROPERTY
  {
    id: 64,
    section: 'Personal Property',
    question: 'Do you own any vehicles?',
    field: 'ownsVehicles',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'basic',
  },
  {
    id: 65,
    section: 'Personal Property',
    question: 'If yes, list make, model, year, and estimated value',
    field: 'vehiclesDetails',
    type: 'textarea',
    required: false,
    tier: 'basic',
  },
  {
    id: 66,
    section: 'Personal Property',
    question: 'Do you own jewelry, art, or collectibles of significant value?',
    field: 'hasJewelryArt',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 67,
    section: 'Personal Property',
    question: 'If yes, provide details and estimated values',
    field: 'jewelryArtDetails',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'Include descriptions and approximate values for insurance purposes',
  },
  {
    id: 68,
    section: 'Personal Property',
    question: 'Are there specific personal items you wish to leave to specific people?',
    field: 'sentimentalItems',
    type: 'textarea',
    required: false,
    tier: 'basic',
    helpText: 'e.g., "My watch to John, my jewelry to Mary"',
  },
  {
    id: 69,
    section: 'Personal Property',
    question: 'Do you own any pets?',
    field: 'hasPets',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'basic',
  },
  {
    id: 70,
    section: 'Personal Property',
    question: 'If yes, list pets and who should care for them',
    field: 'petsDetails',
    type: 'textarea',
    required: false,
    tier: 'basic',
    helpText: 'Include pet names, types, and preferred caregiver',
  },
  {
    id: 71,
    section: 'Personal Property',
    question: 'Should funds be provided for pet care? If yes, how much?',
    field: 'petCareFunds',
    type: 'text',
    required: false,
    tier: 'advanced',
    helpText: 'e.g., "$5,000" or "sufficient funds for lifetime care"',
  },

  // SECTION 9: DEBTS & LIABILITIES
  {
    id: 72,
    section: 'Debts & Liabilities',
    question: 'List all mortgages (property, lender, approximate balance)',
    field: 'mortgagesList',
    type: 'textarea',
    required: false,
    tier: 'basic',
  },
  {
    id: 73,
    section: 'Debts & Liabilities',
    question: 'Do you have any personal loans?',
    field: 'hasPersonalLoans',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'basic',
  },
  {
    id: 74,
    section: 'Debts & Liabilities',
    question: 'If yes, provide details (lender, balance, terms)',
    field: 'personalLoansDetails',
    type: 'textarea',
    required: false,
    tier: 'basic',
  },
  {
    id: 75,
    section: 'Debts & Liabilities',
    question: 'Do you have credit card debts?',
    field: 'hasCreditCardDebt',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'basic',
  },
  {
    id: 76,
    section: 'Debts & Liabilities',
    question: 'If yes, approximate total credit card debt',
    field: 'creditCardDebtTotal',
    type: 'text',
    required: false,
    tier: 'basic',
  },
  {
    id: 77,
    section: 'Debts & Liabilities',
    question: 'Do you have any other debts (business loans, tax liabilities, etc.)?',
    field: 'otherDebts',
    type: 'textarea',
    required: false,
    tier: 'advanced',
  },

  // SECTION 10: EXECUTOR & TRUSTEE (Legal Requirements)
  {
    id: 78,
    section: 'Executor & Trustee',
    question: 'Who should be your executor (estate trustee)? Provide full name, address, and relationship.',
    field: 'primaryExecutor',
    type: 'textarea',
    required: true,
    tier: 'basic',
    legalNote: 'Executor must be named and must be 18+ years old',
  },
  {
    id: 79,
    section: 'Executor & Trustee',
    question: 'Have you discussed this with the primary executor and confirmed their willingness?',
    field: 'executorWilling',
    type: 'select',
    options: ['Yes', 'No', 'Not yet'],
    required: true,
    tier: 'basic',
    helpText: 'It\'s important to confirm before naming them',
  },
  {
    id: 80,
    section: 'Executor & Trustee',
    question: 'Who should be your alternate executor if the primary cannot serve?',
    field: 'alternateExecutor',
    type: 'textarea',
    required: true,
    tier: 'basic',
    legalNote: 'Always have a backup executor named',
  },
  {
    id: 81,
    section: 'Executor & Trustee',
    question: 'Should your executor receive compensation?',
    field: 'executorCompensation',
    type: 'select',
    options: ['Yes', 'No', 'Reasonable compensation from estate'],
    required: true,
    tier: 'advanced',
    helpText: 'Executors are entitled to reasonable compensation under Ontario law',
  },
  {
    id: 82,
    section: 'Executor & Trustee',
    question: 'If yes, how much or what percentage of the estate?',
    field: 'executorCompensationAmount',
    type: 'text',
    required: false,
    tier: 'advanced',
    helpText: 'e.g., "$5,000" or "2.5% of estate value"',
  },
  {
    id: 83,
    section: 'Executor & Trustee',
    question: 'Should your executor have broad powers or limited powers?',
    field: 'executorPowers',
    type: 'select',
    options: ['Broad powers', 'Limited powers', 'Specify restrictions'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 84,
    section: 'Executor & Trustee',
    question: 'If limited, specify any restrictions on executor powers',
    field: 'executorRestrictions',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'e.g., "Cannot sell primary residence without court approval"',
  },
  {
    id: 85,
    section: 'Executor & Trustee',
    question: 'Should there be a trust manager separate from the executor?',
    field: 'hasSeparateTrustManager',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 86,
    section: 'Executor & Trustee',
    question: 'If yes, who should be the trust manager?',
    field: 'trustManager',
    type: 'textarea',
    required: false,
    tier: 'advanced',
  },

  // SECTION 11: GUARDIANSHIP & SPECIAL PROVISIONS
  {
    id: 87,
    section: 'Guardianship & Trusts',
    question: 'Do you have minor children (under 18)?',
    field: 'hasMinorChildren',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'basic',
    legalNote: 'Guardianship designation is critical for minor children',
  },
  {
    id: 88,
    section: 'Guardianship & Trusts',
    question: 'If yes, who should be their guardian? Provide full name and address.',
    field: 'guardians',
    type: 'textarea',
    required: false,
    tier: 'basic',
    helpText: 'Choose someone you trust completely to raise your children',
  },
  {
    id: 89,
    section: 'Guardianship & Trusts',
    question: 'Have you discussed guardianship with the proposed guardian?',
    field: 'guardianConfirmed',
    type: 'select',
    options: ['Yes', 'No', 'Not yet'],
    required: false,
    tier: 'basic',
  },
  {
    id: 90,
    section: 'Guardianship & Trusts',
    question: 'Who should be the alternate guardian if the primary cannot serve?',
    field: 'alternateGuardian',
    type: 'textarea',
    required: false,
    tier: 'basic',
  },
  {
    id: 91,
    section: 'Guardianship & Trusts',
    question: 'Do you want to establish trusts for any beneficiaries?',
    field: 'hasSpecialTrusts',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
    helpText: 'e.g., Henson Trust for special needs, age-based trusts',
  },
  {
    id: 92,
    section: 'Guardianship & Trusts',
    question: 'If yes, provide details (type of trust, beneficiary, conditions)',
    field: 'specialTrustsDetails',
    type: 'textarea',
    required: false,
    tier: 'advanced',
  },
  {
    id: 93,
    section: 'Guardianship & Trusts',
    question: 'Should any beneficiaries receive their inheritance in stages (e.g., age 25, 30, 35)?',
    field: 'stagedInheritance',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'e.g., "25% at age 25, 50% at age 30, remainder at age 35"',
  },
  {
    id: 94,
    section: 'Guardianship & Trusts',
    question: 'Are there any conditions or restrictions on inheritance?',
    field: 'inheritanceConditions',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'e.g., "Only if they complete university", "If they remain sober"',
  },

  // SECTION 12: BENEFICIARIES & DISTRIBUTION
  {
    id: 95,
    section: 'Beneficiaries & Distribution',
    question: 'Who should be your primary beneficiary (the person who receives most of your estate)?',
    field: 'primaryBeneficiary',
    type: 'textarea',
    required: true,
    tier: 'basic',
    helpText: 'Provide full name and relationship',
  },
  {
    id: 96,
    section: 'Beneficiaries & Distribution',
    question: 'What percentage of your estate should your primary beneficiary receive?',
    field: 'primaryBeneficiaryPercentage',
    type: 'text',
    required: true,
    tier: 'basic',
    helpText: 'e.g., "50%" or "entire estate"',
  },
  {
    id: 97,
    section: 'Beneficiaries & Distribution',
    question: 'List any other beneficiaries and their inheritance percentages',
    field: 'otherBeneficiaries',
    type: 'textarea',
    required: false,
    tier: 'basic',
    helpText: 'Format: Name (Relationship) - Percentage',
  },
  {
    id: 98,
    section: 'Beneficiaries & Distribution',
    question: 'Do you want to make any charitable donations?',
    field: 'hasCharitableDonations',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 99,
    section: 'Beneficiaries & Distribution',
    question: 'If yes, list charities and donation amounts',
    field: 'charitableDonations',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'Include registered charity numbers if available',
  },
  {
    id: 100,
    section: 'Beneficiaries & Distribution',
    question: 'What should happen to your estate if a beneficiary dies before you?',
    field: 'contingencyPlan',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'e.g., "Their share goes to their children" or "Back to remaining beneficiaries"',
  },

  // SECTION 13: FINAL WISHES & SPECIAL INSTRUCTIONS
  {
    id: 101,
    section: 'Final Wishes',
    question: 'Do you have any funeral or burial preferences?',
    field: 'funeralPreferences',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'e.g., "Cremation, no service" or "Traditional funeral"',
  },
  {
    id: 102,
    section: 'Final Wishes',
    question: 'Do you want to donate your body to medical science?',
    field: 'bodyDonation',
    type: 'select',
    options: ['Yes', 'No', 'Unsure'],
    required: false,
    tier: 'advanced',
  },
  {
    id: 103,
    section: 'Final Wishes',
    question: 'Are there any other special wishes or instructions for your estate?',
    field: 'specialWishes',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'Any final instructions or wishes for your executor',
  },
  {
    id: 104,
    section: 'Final Wishes',
    question: 'Should any specific items or heirlooms have special instructions?',
    field: 'heirloomInstructions',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'e.g., "My grandfather\'s watch should go to my eldest son"',
  },

  // SECTION 14: LEGAL & TAX CONSIDERATIONS
  {
    id: 105,
    section: 'Legal & Tax',
    question: 'Do you have any pending legal disputes or lawsuits?',
    field: 'hasLegalDisputes',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
    legalNote: 'Legal disputes may affect estate administration',
  },
  {
    id: 106,
    section: 'Legal & Tax',
    question: 'If yes, provide details',
    field: 'legalDisputesDetails',
    type: 'textarea',
    required: false,
    tier: 'advanced',
  },
  {
    id: 107,
    section: 'Legal & Tax',
    question: 'Have you filed all required tax returns?',
    field: 'taxReturnsFiledUpToDate',
    type: 'select',
    options: ['Yes', 'No', 'Unsure'],
    required: true,
    tier: 'advanced',
    legalNote: 'Outstanding tax liabilities become estate liabilities',
  },
  {
    id: 108,
    section: 'Legal & Tax',
    question: 'Do you have any outstanding tax liabilities?',
    field: 'hasOutstandingTaxes',
    type: 'select',
    options: ['Yes', 'No', 'Unsure'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 109,
    section: 'Legal & Tax',
    question: 'If yes, provide details and estimated amounts',
    field: 'outstandingTaxesDetails',
    type: 'textarea',
    required: false,
    tier: 'advanced',
  },
  {
    id: 110,
    section: 'Legal & Tax',
    question: 'Have you previously made a will or estate plan?',
    field: 'previousWill',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
    legalNote: 'Previous wills may need to be revoked',
  },
  {
    id: 111,
    section: 'Legal & Tax',
    question: 'If yes, when was it made and where is it stored?',
    field: 'previousWillDetails',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'Include approximate date and location (lawyer, bank, home, etc.)',
  },
  {
    id: 112,
    section: 'Legal & Tax',
    question: 'Do you want to revoke all previous wills?',
    field: 'revokeAllPreviousWills',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
    legalNote: 'Standard practice to revoke previous wills',
  },
];

// ============================================================================
// POA PROPERTY QUESTIONS - Powers of Attorney Act Compliant
// ============================================================================

export const POA_PROPERTY_QUESTIONS: Question[] = [
  // SECTION 1: GRANTOR INFORMATION
  {
    id: 1,
    section: 'Grantor Information',
    question: 'What is your full legal name?',
    field: 'grantorFullName',
    type: 'text',
    required: true,
    tier: 'basic',
    legalNote: 'Grantor is the person granting the power of attorney',
  },
  {
    id: 2,
    section: 'Grantor Information',
    question: 'What is your date of birth?',
    field: 'grantorDateOfBirth',
    type: 'date',
    required: true,
    tier: 'basic',
    legalNote: 'Must be 18+ years old to grant a POA',
  },
  {
    id: 3,
    section: 'Grantor Information',
    question: 'What is your residential address in Ontario?',
    field: 'grantorAddress',
    type: 'textarea',
    required: true,
    tier: 'basic',
  },
  {
    id: 4,
    section: 'Grantor Information',
    question: 'Are you of sound mind and free from undue influence?',
    field: 'soundMind',
    type: 'select',
    options: ['Yes', 'No', 'Unsure'],
    required: true,
    tier: 'basic',
    legalNote: 'Grantor must have capacity to grant POA',
  },

  // SECTION 2: ATTORNEY INFORMATION
  {
    id: 5,
    section: 'Attorney (Agent)',
    question: 'Who should be your attorney (agent) for property matters?',
    field: 'primaryAttorney',
    type: 'textarea',
    required: true,
    tier: 'basic',
    helpText: 'Provide full name, address, phone, and relationship',
    legalNote: 'Attorney must be 18+ and have capacity to act',
  },
  {
    id: 6,
    section: 'Attorney (Agent)',
    question: 'Have you discussed this with your attorney and confirmed their willingness?',
    field: 'attorneyWilling',
    type: 'select',
    options: ['Yes', 'No', 'Not yet'],
    required: true,
    tier: 'basic',
  },
  {
    id: 7,
    section: 'Attorney (Agent)',
    question: 'Who should be your alternate attorney if the primary cannot serve?',
    field: 'alternateAttorney',
    type: 'textarea',
    required: true,
    tier: 'basic',
    helpText: 'Provide full name, address, phone, and relationship',
  },
  {
    id: 8,
    section: 'Attorney (Agent)',
    question: 'Should your attorneys act jointly (both must agree) or jointly and severally (either can act alone)?',
    field: 'attorneyAuthority',
    type: 'select',
    options: ['Jointly (both must agree)', 'Jointly and severally (either can act)', 'Sequentially (alternate if primary unavailable)'],
    required: true,
    tier: 'advanced',
    legalNote: 'Determines how multiple attorneys exercise authority',
  },

  // SECTION 3: SCOPE OF POWERS
  {
    id: 9,
    section: 'Powers & Authority',
    question: 'Should your attorney have broad powers over all property?',
    field: 'broadPowers',
    type: 'select',
    options: ['Yes', 'No', 'Limited powers'],
    required: true,
    tier: 'basic',
    legalNote: 'Broad powers include managing all real and personal property',
  },
  {
    id: 10,
    section: 'Powers & Authority',
    question: 'If limited, which specific powers should your attorney have?',
    field: 'limitedPowers',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'e.g., "Only manage bank accounts", "Cannot sell real property"',
  },
  {
    id: 11,
    section: 'Powers & Authority',
    question: 'Should your attorney be able to sell your primary residence?',
    field: 'canSellPrimaryResidence',
    type: 'select',
    options: ['Yes', 'No', 'Only with court approval'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 12,
    section: 'Powers & Authority',
    question: 'Should your attorney be able to sell investment properties?',
    field: 'canSellInvestmentProperties',
    type: 'select',
    options: ['Yes', 'No', 'Only with court approval'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 13,
    section: 'Powers & Authority',
    question: 'Should your attorney be able to gift money or property?',
    field: 'canMakeGifts',
    type: 'select',
    options: ['Yes', 'No', 'Limited amount per year'],
    required: true,
    tier: 'advanced',
    legalNote: 'Gifts require specific authorization under Powers of Attorney Act',
  },
  {
    id: 14,
    section: 'Powers & Authority',
    question: 'If yes to gifts, what is the maximum amount per year?',
    field: 'giftLimit',
    type: 'text',
    required: false,
    tier: 'advanced',
    helpText: 'e.g., "$5,000 per year" or "reasonable gifts"',
  },
  {
    id: 15,
    section: 'Powers & Authority',
    question: 'Should your attorney be able to make investments?',
    field: 'canMakeInvestments',
    type: 'select',
    options: ['Yes', 'No', 'Conservative investments only'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 16,
    section: 'Powers & Authority',
    question: 'Should your attorney be able to borrow money on your behalf?',
    field: 'canBorrow',
    type: 'select',
    options: ['Yes', 'No', 'Limited amount'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 17,
    section: 'Powers & Authority',
    question: 'If yes, what is the maximum borrowing limit?',
    field: 'borrowingLimit',
    type: 'text',
    required: false,
    tier: 'advanced',
  },

  // SECTION 4: REAL PROPERTY
  {
    id: 18,
    section: 'Real Property',
    question: 'List all real property you own (address, approximate value)',
    field: 'realPropertyList',
    type: 'textarea',
    required: false,
    tier: 'basic',
  },
  {
    id: 19,
    section: 'Real Property',
    question: 'Are there any restrictions on how your attorney can manage real property?',
    field: 'realPropertyRestrictions',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'e.g., "Cannot sell cottage" or "Cannot refinance mortgage"',
  },

  // SECTION 5: FINANCIAL ACCOUNTS
  {
    id: 20,
    section: 'Financial Accounts',
    question: 'List all bank accounts (institution, account type)',
    field: 'bankAccountsList',
    type: 'textarea',
    required: false,
    tier: 'basic',
    helpText: 'Do not include account numbers',
  },
  {
    id: 21,
    section: 'Financial Accounts',
    question: 'List all investment accounts (institution, account type)',
    field: 'investmentAccountsList',
    type: 'textarea',
    required: false,
    tier: 'basic',
  },
  {
    id: 22,
    section: 'Financial Accounts',
    question: 'List all retirement accounts (RRSPs, TFSAs, pensions)',
    field: 'retirementAccountsList',
    type: 'textarea',
    required: false,
    tier: 'advanced',
  },

  // SECTION 6: BUSINESS INTERESTS
  {
    id: 23,
    section: 'Business Interests',
    question: 'Do you own or have an interest in any business?',
    field: 'ownsBusinessInterest',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 24,
    section: 'Business Interests',
    question: 'If yes, describe the business and your ownership percentage',
    field: 'businessDetails',
    type: 'textarea',
    required: false,
    tier: 'advanced',
  },
  {
    id: 25,
    section: 'Business Interests',
    question: 'Should your attorney be able to manage your business?',
    field: 'attorneyCanManageBusiness',
    type: 'select',
    options: ['Yes', 'No', 'Limited authority'],
    required: false,
    tier: 'advanced',
  },

  // SECTION 7: EFFECTIVE DATE & TERMINATION
  {
    id: 26,
    section: 'Effective Date',
    question: 'When should this power of attorney become effective?',
    field: 'effectiveDate',
    type: 'select',
    options: ['Immediately', 'When I become incapable', 'Specific date'],
    required: true,
    tier: 'basic',
    legalNote: 'Immediate POAs are "springing" POAs; conditional ones are "springing" POAs',
  },
  {
    id: 27,
    section: 'Effective Date',
    question: 'If specific date, what is the date?',
    field: 'specificEffectiveDate',
    type: 'date',
    required: false,
    tier: 'advanced',
  },
  {
    id: 28,
    section: 'Effective Date',
    question: 'When should this power of attorney terminate?',
    field: 'terminationCondition',
    type: 'select',
    options: ['When I die', 'When I revoke it', 'On a specific date', 'When I become incapable (if springing)'],
    required: true,
    tier: 'advanced',
  },

  // SECTION 8: COMPENSATION & ACCOUNTABILITY
  {
    id: 29,
    section: 'Compensation',
    question: 'Should your attorney receive compensation?',
    field: 'attorneyCompensation',
    type: 'select',
    options: ['Yes', 'No', 'Reasonable compensation'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 30,
    section: 'Compensation',
    question: 'If yes, how much or what percentage?',
    field: 'compensationAmount',
    type: 'text',
    required: false,
    tier: 'advanced',
  },
  {
    id: 31,
    section: 'Compensation',
    question: 'Should your attorney be required to keep detailed records?',
    field: 'requireRecords',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
    legalNote: 'Attorneys have a fiduciary duty to account for their actions',
  },
  {
    id: 32,
    section: 'Compensation',
    question: 'Should your attorney be required to report to anyone?',
    field: 'reportingRequirement',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'e.g., "Report to my daughter annually", "Report to my accountant"',
  },

  // SECTION 9: SPECIAL INSTRUCTIONS
  {
    id: 33,
    section: 'Special Instructions',
    question: 'Are there any special instructions or restrictions for your attorney?',
    field: 'specialInstructions',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'Any specific wishes or limitations on attorney authority',
  },
  {
    id: 34,
    section: 'Special Instructions',
    question: 'Should your attorney consult with anyone before making major decisions?',
    field: 'consultationRequirement',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'e.g., "Consult with my accountant before selling investments"',
  },
];

// ============================================================================
// POA PERSONAL CARE QUESTIONS - Health Care Consent Act Compliant
// ============================================================================

export const POA_PERSONAL_CARE_QUESTIONS: Question[] = [
  // SECTION 1: GRANTOR INFORMATION
  {
    id: 1,
    section: 'Grantor Information',
    question: 'What is your full legal name?',
    field: 'grantorFullName',
    type: 'text',
    required: true,
    tier: 'basic',
  },
  {
    id: 2,
    section: 'Grantor Information',
    question: 'What is your date of birth?',
    field: 'grantorDateOfBirth',
    type: 'date',
    required: true,
    tier: 'basic',
    legalNote: 'Must be 16+ years old to grant a POA for Personal Care',
  },
  {
    id: 3,
    section: 'Grantor Information',
    question: 'What is your residential address in Ontario?',
    field: 'grantorAddress',
    type: 'textarea',
    required: true,
    tier: 'basic',
  },
  {
    id: 4,
    section: 'Grantor Information',
    question: 'Are you of sound mind and free from undue influence?',
    field: 'soundMind',
    type: 'select',
    options: ['Yes', 'No', 'Unsure'],
    required: true,
    tier: 'basic',
    legalNote: 'Grantor must have capacity under Health Care Consent Act',
  },

  // SECTION 2: ATTORNEY (AGENT) INFORMATION
  {
    id: 5,
    section: 'Attorney (Agent)',
    question: 'Who should be your attorney (agent) for personal care decisions?',
    field: 'primaryAttorney',
    type: 'textarea',
    required: true,
    tier: 'basic',
    helpText: 'Provide full name, address, phone, and relationship',
    legalNote: 'Attorney must be 18+ and have capacity to act',
  },
  {
    id: 6,
    section: 'Attorney (Agent)',
    question: 'Have you discussed this with your attorney and confirmed their willingness?',
    field: 'attorneyWilling',
    type: 'select',
    options: ['Yes', 'No', 'Not yet'],
    required: true,
    tier: 'basic',
  },
  {
    id: 7,
    section: 'Attorney (Agent)',
    question: 'Who should be your alternate attorney if the primary cannot serve?',
    field: 'alternateAttorney',
    type: 'textarea',
    required: true,
    tier: 'basic',
  },

  // SECTION 3: HEALTHCARE DECISIONS
  {
    id: 8,
    section: 'Healthcare Decisions',
    question: 'Should your attorney be able to make all healthcare decisions?',
    field: 'broadHealthcarePowers',
    type: 'select',
    options: ['Yes', 'No', 'Limited decisions'],
    required: true,
    tier: 'basic',
    legalNote: 'Includes consent to treatment, admission to facilities, etc.',
  },
  {
    id: 9,
    section: 'Healthcare Decisions',
    question: 'If limited, which specific healthcare decisions can your attorney make?',
    field: 'limitedHealthcarePowers',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'e.g., "Only routine medical treatment", "Cannot consent to surgery"',
  },
  {
    id: 10,
    section: 'Healthcare Decisions',
    question: 'Should your attorney be able to consent to surgery?',
    field: 'canConsentToSurgery',
    type: 'select',
    options: ['Yes', 'No', 'Only emergency surgery'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 11,
    section: 'Healthcare Decisions',
    question: 'Should your attorney be able to consent to psychiatric treatment?',
    field: 'canConsentToPsychiatricTreatment',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
    legalNote: 'Psychiatric treatment has special protections under law',
  },
  {
    id: 12,
    section: 'Healthcare Decisions',
    question: 'Should your attorney be able to consent to electroconvulsive therapy (ECT)?',
    field: 'canConsentToECT',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
    legalNote: 'ECT requires specific authorization',
  },
  {
    id: 13,
    section: 'Healthcare Decisions',
    question: 'Should your attorney be able to consent to medication?',
    field: 'canConsentToMedication',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'basic',
  },
  {
    id: 14,
    section: 'Healthcare Decisions',
    question: 'Should your attorney be able to refuse life-sustaining treatment?',
    field: 'canRefuseLifeSustaining',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
    legalNote: 'This is a critical decision - consider carefully',
  },

  // SECTION 4: PERSONAL CARE & LIVING ARRANGEMENTS
  {
    id: 15,
    section: 'Personal Care',
    question: 'Should your attorney be able to decide where you live?',
    field: 'canDecideLivingArrangements',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'basic',
    helpText: 'Includes decisions about nursing homes, assisted living, etc.',
  },
  {
    id: 16,
    section: 'Personal Care',
    question: 'Do you have preferences about where you want to live if you need care?',
    field: 'livingPreferences',
    type: 'textarea',
    required: false,
    tier: 'basic',
    helpText: 'e.g., "Prefer to stay at home", "Willing to go to nursing home if necessary"',
  },
  {
    id: 17,
    section: 'Personal Care',
    question: 'Should your attorney be able to make decisions about personal hygiene and grooming?',
    field: 'canMakePersonalCareDecisions',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 18,
    section: 'Personal Care',
    question: 'Should your attorney be able to make decisions about nutrition and diet?',
    field: 'canMakeDietDecisions',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 19,
    section: 'Personal Care',
    question: 'Should your attorney be able to make decisions about rehabilitation and therapy?',
    field: 'canMakeRehabDecisions',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
  },

  // SECTION 5: END-OF-LIFE DECISIONS
  {
    id: 20,
    section: 'End-of-Life Decisions',
    question: 'Do you have any wishes about end-of-life care?',
    field: 'hasEndOfLifeWishes',
    type: 'select',
    options: ['Yes', 'No'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 21,
    section: 'End-of-Life Decisions',
    question: 'If yes, describe your end-of-life preferences',
    field: 'endOfLifeWishes',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'e.g., "No artificial life support", "Palliative care only", "DNR order"',
  },
  {
    id: 22,
    section: 'End-of-Life Decisions',
    question: 'Do you want to donate your organs?',
    field: 'organDonation',
    type: 'select',
    options: ['Yes', 'No', 'Undecided'],
    required: true,
    tier: 'advanced',
  },
  {
    id: 23,
    section: 'End-of-Life Decisions',
    question: 'Do you want to donate your body to medical science?',
    field: 'bodyDonation',
    type: 'select',
    options: ['Yes', 'No', 'Undecided'],
    required: true,
    tier: 'advanced',
  },

  // SECTION 6: MEDICAL INFORMATION
  {
    id: 24,
    section: 'Medical Information',
    question: 'List your current healthcare providers (doctors, specialists)',
    field: 'healthcareProviders',
    type: 'textarea',
    required: false,
    tier: 'basic',
    helpText: 'Include names and specialties',
  },
  {
    id: 25,
    section: 'Medical Information',
    question: 'List any allergies or adverse reactions to medications',
    field: 'allergies',
    type: 'textarea',
    required: false,
    tier: 'basic',
    helpText: 'Critical for healthcare providers to know',
  },
  {
    id: 26,
    section: 'Medical Information',
    question: 'List any chronic conditions or ongoing treatments',
    field: 'chronicConditions',
    type: 'textarea',
    required: false,
    tier: 'basic',
  },
  {
    id: 27,
    section: 'Medical Information',
    question: 'List all current medications',
    field: 'currentMedications',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'Include medication names and dosages',
  },
  {
    id: 28,
    section: 'Medical Information',
    question: 'Do you have any religious or cultural beliefs that affect healthcare decisions?',
    field: 'religiousCulturalBeliefs',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'e.g., "No blood transfusions", "Specific dietary requirements"',
  },

  // SECTION 7: EFFECTIVE DATE & TERMINATION
  {
    id: 29,
    section: 'Effective Date',
    question: 'When should this power of attorney become effective?',
    field: 'effectiveDate',
    type: 'select',
    options: ['Immediately', 'When I become incapable', 'Specific date'],
    required: true,
    tier: 'basic',
    legalNote: 'Personal Care POAs are typically "springing" (effective when incapable)',
  },
  {
    id: 30,
    section: 'Effective Date',
    question: 'If specific date, what is the date?',
    field: 'specificEffectiveDate',
    type: 'date',
    required: false,
    tier: 'advanced',
  },
  {
    id: 31,
    section: 'Effective Date',
    question: 'When should this power of attorney terminate?',
    field: 'terminationCondition',
    type: 'select',
    options: ['When I die', 'When I revoke it', 'When I regain capacity', 'On a specific date'],
    required: true,
    tier: 'advanced',
  },

  // SECTION 8: SPECIAL INSTRUCTIONS
  {
    id: 32,
    section: 'Special Instructions',
    question: 'Are there any special instructions or restrictions for your attorney?',
    field: 'specialInstructions',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'Any specific wishes or limitations',
  },
  {
    id: 33,
    section: 'Special Instructions',
    question: 'Should your attorney consult with anyone before making major decisions?',
    field: 'consultationRequirement',
    type: 'textarea',
    required: false,
    tier: 'advanced',
    helpText: 'e.g., "Consult with my family", "Consult with my doctor"',
  },
  {
    id: 34,
    section: 'Special Instructions',
    question: 'Are there any people who should NOT be involved in your care?',
    field: 'excludedPeople',
    type: 'textarea',
    required: false,
    tier: 'advanced',
  },
];

export const DOCUMENT_QUESTIONS: Record<string, DocumentQuestionSet> = {
  will: {
    documentType: 'will',
    questions: WILL_QUESTIONS,
  },
  'poa-property': {
    documentType: 'poa-property',
    questions: POA_PROPERTY_QUESTIONS,
  },
  'poa-personal-care': {
    documentType: 'poa-personal-care',
    questions: POA_PERSONAL_CARE_QUESTIONS,
  },
};

/**
 * Get questions for a specific document type and tier
 */
export function getQuestionsForTier(documentType: string, tier: 'basic' | 'advanced' | 'all' = 'all'): Question[] {
  const questionSet = DOCUMENT_QUESTIONS[documentType];
  if (!questionSet) {
    return [];
  }

  if (tier === 'all') {
    return questionSet.questions;
  }

  return questionSet.questions.filter(q => q.tier === tier || (tier === 'basic' && q.tier === 'basic'));
}

/**
 * Get question count by tier
 */
export function getQuestionCountByTier(documentType: string): { basic: number; advanced: number; total: number } {
  const questionSet = DOCUMENT_QUESTIONS[documentType];
  if (!questionSet) {
    return { basic: 0, advanced: 0, total: 0 };
  }

  const basic = questionSet.questions.filter(q => q.tier === 'basic').length;
  const advanced = questionSet.questions.filter(q => q.tier === 'advanced').length;

  return {
    basic,
    advanced,
    total: basic + advanced,
  };
}
